language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  # Scikit-Learn does not depend on thoses, they might be miss ordered by pip
  - pip install -U pip
  - pip install --only-binary=numpy,scipy numpy scipy
  - pip install .
  - pip install -r requirements.txt
# command to run tests
script:
  - python setup.py nosetests
services:
  - mongodb
