# -*- coding: utf-8 -*-
#
# Chocolate documentation build configuration file, created by
# sphinx-quickstart on Fri Dec 30 13:21:43 2016.
#
# This file is execfile()d with the current directory set to its containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

import sys, time

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
sys.path.append("..")
#sys.path.append(os.path.abspath('_ext/'))

import chocolate

# -- General configuration -----------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be extensions
# coming with Sphinx (named 'sphinx.ext.*') or your custom ones

extensions = ['sphinx.ext.autodoc', 'sphinx.ext.autosectionlabel',
              'sphinx.ext.autosummary', 'sphinx.ext.doctest',
              'sphinx.ext.todo', 'sphinx.ext.mathjax', 'sphinx.ext.intersphinx',
              'sphinx.ext.extlinks', 'sphinx.ext.viewcode', 'sphinx.ext.napoleon'] 

try:
    import matplotlib
except:
    pass
else:
      extensions += ['matplotlib.sphinxext.only_directives',
                     'matplotlib.sphinxext.plot_directive']

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix of source filenames.
source_suffix = '.rst'

# The encoding of source files.
#source_encoding = 'utf-8'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = u'Chocolate'
copyright = u'2016-%s, NovaSyst' % time.strftime('%Y')

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = chocolate.__version__
# The full version, including alpha/beta/rc tags.
release = chocolate.__revision__

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#language = None

# There are two options for replacing |today|: either, you set today to some
# non-false value, then it is used:
#today = ''
# Else, today_fmt is used as the format for a strftime call.
#today_fmt = '%B %d, %Y'

# List of documents that shouldn't be included in the build.
#unused_docs = []

# List of directories, relative to source directory, that shouldn't be searched
# for source files.
exclude_trees = ['_build']

# The reST default role (used for this markup: `text`) to use for all documents.
#default_role = None

# If true, '()' will be appended to :func: etc. cross-reference text.
#add_function_parentheses = True

# If true, the current module name will be prepended to all description
# unit titles (such as .. function::).
#add_module_names = True

# If true, sectionauthor and moduleauthor directives will be shown in the
# output. They are ignored by default.
#show_authors = False

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'default'

# A list of ignored prefixes for module index sorting.
#modindex_common_prefix = []

# If true, the todo will be printed in the documentation
todo_include_todos = True

# Search in python documentation
intersphinx_mapping = {'python' : ('https://docs.python.org/3', None),
                       'numpy'  : ('http://docs.scipy.org/doc/numpy', None),
                       'pandas': ('http://pandas-docs.github.io/pandas-docs-travis/', None)}

# Reload the cached values every 5 days
intersphinx_cache_limit = 5

# -- Options for pyplot extension ----------------------------------------------

# Default value for the include-source option
plot_include_source = False

# Code that should be executed before each plot.
#plot_pre_code

# Base directory, to which ``plot::`` file names are relative
# to.  (If None or empty, file names are relative to the 
# directory where the file containing the directive is.)
#plot_basedir

#  Whether to show links to the files in HTML.
plot_html_show_formats = True

# Add any paths that contain custom themes here, relative to this directory.
html_theme_path = ["_themes"]

def setup(app):
  app.add_stylesheet( "css/aiw.css" )

# The theme to use for HTML and HTML Help pages.  Major themes that come with
# Sphinx are currently 'classic' and 'alabaster'.
html_theme = 'sphinx_rtd_theme'
# html_theme = 'alabaster'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
# html_theme_options = {
#     'collapse_navigation': False,
#     'display_version': False,
#     'navigation_depth': 2,
# }

# The name for this set of Sphinx documents.  If None, it defaults to
# "<project> v<release> documentation".
#html_title = None

# A shorter title for the navigation bar.  Default is the same as html_title.
#html_short_title = None

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
#html_logo = ""

# The name of an image file (within the static path) to use as favicon of the
# docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
# html_favicon = "deap_orange_icon_32.ico"

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# If not '', a 'Last updated on:' timestamp is inserted at every page bottom,
# using the given strftime format.
html_last_updated_fmt = '%b %d, %Y'

# Custom sidebar templates, maps document names to template names.
# html_sidebars = {}

# Additional templates that should be rendered to pages, maps page names to
# template names.
# html_additional_pages = {}

# If false, no module index is generated.
#html_use_modindex = True

# If false, no index is generated.
# html_use_index = True

# If true, the index is split into individual pages for each letter.
# html_split_index = True

# If true, links to the reST sources are added to the pages.
#html_show_sourcelink = True

# If true, an OpenSearch description file will be output, and all pages will
# contain a <link> tag referring to it.  The value of this option must be the
# base URL from which the finished HTML is served.
#html_use_opensearch = ''

# If nonempty, this is the file name suffix for HTML files (e.g. ".xhtml").
#html_file_suffix = ''

# Output file base name for HTML help builder.
htmlhelp_basename = 'Chocolate-doc'

